language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -y -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - "make"
  - "ctest --output-on-failure"
